version: '3'
services: 
  jupyter:
    ports:
    - "8888:8888"
    volumes:
    - ~/dev/ml/domino/notebooks:/notebooks:rw
    - ~/dev/ml/domino/data:/data:rw
    container_name:   jupyter_notebook
    build: .

